### PR TITLE
Fix: fixes issue #20

### LINKED ISSUE #20: Test Failure: Please fix the bug
# Test Failure

The tests have failed on the latest push to the refs/heads/main branch. 

Please review the errors and fix the issues.

## Details

- Commit: cd9605cd53a60de89be1127f3d2aee08be3866de
- Branch: refs/heads/main

## Steps to Reproduce

1. Pull the latest changes from the main branch.
2. Run `npm test` in the `javascript` directory.
3. Review the test failures and correct the issues.

### PR DESCRIPTION
**Pull request by m0xn**
fix #20 

Removed the .toString() method call to avoid integer conversion to string, which ultimately leads to the implementation of the + operator to concatenate the given strings.

Since JavaScript does not support static typing, I've also added a safe guard at the start of the function checking if one or both of the arguments are actually integers at runtime.

If we were to leave the error aside of the equation, I'd suggest using the "arrow function notation" to define the add() function in the following way:

export const add = (a, b) => a + b;

Just to be a little bit more elegant and simple ;)

Thanks for the opportunity to make a little contribution for a repo :)! Looking forward to make good things for open source.

*Sorry for the inconveniences with branch name conventions*

### CODE REVIEW

**Review by alex1yaremchuk — APPROVED** [review]
well done!

**Comment by alex1yaremchuk** [comment]
I merged that in and it works fine. :)

But I cannot see you in the contributors list. 
Maybe its displaying is delayed or chatGPT suggested that maybe email in your local git config differs from the email in the account.
Probably not a big deal, but still.

**Comment by alex1yaremchuk** [comment]
hi, @m0xn ! 

I did a little investigation - it turns out that your local git is set up with not full email - it's missing ".com" part. 

in this repo it is not so important, but it can prevent you from being in contributors list in other projects.

**Comment by m0xn** [comment]
Oh, thanks for pointing that out, I didn't notice it before since I have been using GitHub just for personal projects. Again, thanks for taking the time to look into that, I've already change my config to fix it ;)

**Pull request merged**
