### PR TITLE
fix: Fixes issue#17

### PR DESCRIPTION
**Pull request by brrkak**

### CODE REVIEW

**Comment by alex1yaremchuk** [comment]
Hi @brrkak ! 

why did you close the pull request? 
changes look great!

it didn't get merge into the codebase. 

Shall we re-open it and merge (closed by mistake) or you've changed your mind on participation?

**Comment by brrkak** [comment]
"I didn't know if it was okay to make a pull request to the main branch! I've reopened it, so I would appreciate it if you could check it again!"

**Review by alex1yaremchuk — APPROVED** [review]

**Comment by alex1yaremchuk** [comment]
I approved the changes, you can merge it now, or I can do it myself - if you prefer it. 

Thank you for participation!

**Comment by brrkak** [comment]
I don't have permission to merge, so I would appreciate it if you could handle that!

**Comment by alex1yaremchuk** [comment]
> I don't have permission to merge, so I would appreciate it if you could handle that!

Great, done! 
I didn't know that about permissions, good to know. 

check out [results](https://alex1yaremchuk.github.io/first-pull-request/index.html)

sorry, I'll have to break it again in some time. 

thanks again for your collaboration!

**Pull request merged**
